# Generated by Django 5.0.4 on 2024-04-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description provided."),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("M", "Men"), ("W", "Women")], default="M", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product", name="quantity", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default="One Size", max_length=10),
        ),
    ]
