# Generated by Django 5.0.1 on 2024-04-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password_hash',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
