# Generated by Django 5.0.1 on 2024-04-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_password_hash_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password_hash',
            new_name='password',
        ),
    ]
