# Generated by Django 5.0.1 on 2024-04-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
