# Generated by Django 4.2.11 on 2024-04-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0017_remove_customer_last_login_alter_customer_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
            ],
        ),
    ]
