# Generated by Django 5.0.1 on 2024-04-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_costreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
