# Generated by Django 5.0.1 on 2024-04-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_billingaddress_payment_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
